//! Single source of truth for public schema discovery and generation.

#[cfg(feature = "schemas")]
use super::{
    BackendOutputManifest, CanonicalExampleManifest, CompatibilityPolicy, CompatibilityReport,
    MigrationManifest, SchemaKind, SchemaValidationReport, UnknownEnumDocument,
};
use super::{SchemaCatalog, SchemaDescriptor, SchemaEntry};
use crate::core::SchemaVersion;
use serde_json::Value;

#[cfg(feature = "schemas")]
use schemars::{JsonSchema, schema_for};

#[cfg(feature = "schemas")]
type Generator = fn() -> Value;

#[cfg(feature = "schemas")]
struct Registration {
    descriptor: SchemaDescriptor,
    generator: Generator,
}

pub fn list_schemas() -> Vec<SchemaEntry> {
    schema_catalog()
        .schemas
        .into_iter()
        .map(|descriptor| SchemaEntry {
            name: descriptor.name,
            schema_version: descriptor.schema_version,
        })
        .collect()
}

pub fn schema_catalog() -> SchemaCatalog {
    #[cfg(feature = "schemas")]
    {
        SchemaCatalog::new(
            registrations()
                .into_iter()
                .map(|registration| registration.descriptor)
                .collect(),
        )
    }
    #[cfg(not(feature = "schemas"))]
    {
        SchemaCatalog::new(Vec::new())
    }
}

pub fn schema_descriptor(name: &str) -> Option<SchemaDescriptor> {
    schema_catalog()
        .schemas
        .into_iter()
        .find(|descriptor| descriptor.name == name)
}

#[cfg(feature = "schemas")]
pub fn schema_json(name: &str) -> Option<Value> {
    registrations()
        .into_iter()
        .find(|registration| registration.descriptor.name == name)
        .map(|registration| (registration.generator)())
}

#[cfg(not(feature = "schemas"))]
pub fn schema_json(_name: &str) -> Option<Value> {
    None
}

pub fn schema_json_version(name: &str, version: &str) -> Option<Value> {
    if schema_descriptor(name).is_some_and(|descriptor| descriptor.schema_version == version) {
        return schema_json(name);
    }
    match (name, version) {
        ("text", SchemaVersion::TEXT_V1) => {
            serde_json::from_str(include_str!("../../schemas/grist.text.v1.schema.json")).ok()
        }
        ("csv", SchemaVersion::CSV_V1) => {
            serde_json::from_str(include_str!("../../schemas/grist.csv.v1.schema.json")).ok()
        }
        ("csv-options", "grist/csv-options/v1") => serde_json::from_str(include_str!(
            "../../schemas/grist.csv-options.v1.schema.json"
        ))
        .ok(),
        ("document-graph", SchemaVersion::DOCUMENT_GRAPH_V1) => serde_json::from_str(include_str!(
            "../../schemas/grist.document-graph.v1.schema.json"
        ))
        .ok(),
        ("document-graph-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(
            include_str!("../../schemas/grist.document-graph-envelope.v1.schema.json"),
        )
        .ok(),
        ("serialization-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(
            include_str!("../../schemas/grist.serialization-envelope.v1.schema.json"),
        )
        .ok(),
        ("model-output-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(
            include_str!("../../schemas/grist.model-output-envelope.v1.schema.json"),
        )
        .ok(),
        ("markdown-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(include_str!(
            "../../schemas/grist.markdown-envelope.v1.schema.json"
        ))
        .ok(),
        ("ldgr-projection-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(
            include_str!("../../schemas/grist.ldgr-projection-envelope.v1.schema.json"),
        )
        .ok(),
        ("html-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(include_str!(
            "../../schemas/grist.html-envelope.v1.schema.json"
        ))
        .ok(),
        ("csv-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(include_str!(
            "../../schemas/grist.csv-envelope.v1.schema.json"
        ))
        .ok(),
        ("rust-code-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(include_str!(
            "../../schemas/grist.rust-code-envelope.v1.schema.json"
        ))
        .ok(),
        ("python-code-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(include_str!(
            "../../schemas/grist.python-code-envelope.v1.schema.json"
        ))
        .ok(),
        ("typescript-code-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(
            include_str!("../../schemas/grist.typescript-code-envelope.v1.schema.json"),
        )
        .ok(),
        ("latex-envelope", SchemaVersion::ENVELOPE_V1) => serde_json::from_str(include_str!(
            "../../schemas/grist.latex-envelope.v1.schema.json"
        ))
        .ok(),
        _ => None,
    }
}

#[cfg(feature = "schemas")]
pub fn schema_for_type<T: JsonSchema>() -> Value {
    serde_json::to_value(schema_for!(T)).expect("schema serialization should not fail")
}

#[cfg(feature = "schemas")]
fn registrations() -> Vec<Registration> {
    let mut entries = Vec::new();
    macro_rules! add {
        ($name:literal, $family:literal, $version:expr, $kind:expr, $file:literal, $backend:expr, $type:ty) => {
            entries.push(Registration {
                descriptor: SchemaDescriptor {
                    name: $name.into(),
                    family: $family.into(),
                    schema_version: $version.into(),
                    kind: $kind,
                    file_name: $file.into(),
                    canonical_example: format!(
                        "examples/schema-canonical-examples.v1.json#/examples/{}",
                        $name
                    ),
                    backend_sensitive: $backend,
                },
                generator: schema_for_type::<$type>,
            });
        };
    }

    add!(
        "envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.envelope.v2.schema.json",
        false,
        crate::core::Envelope<Value>
    );
    add!(
        "content-identity",
        "content-identity",
        SchemaVersion::CONTENT_IDENTITY_V1,
        SchemaKind::Contract,
        "grist.content-identity.v1.schema.json",
        false,
        crate::core::ContentIdentity
    );
    add!(
        "source-locator",
        "source-locator",
        SchemaVersion::SOURCE_LOCATOR_V1,
        SchemaKind::Contract,
        "grist.source-locator.v1.schema.json",
        false,
        crate::core::SourceLocator
    );
    add!(
        "citation-anchor",
        "citation-anchor",
        SchemaVersion::CITATION_ANCHOR_V1,
        SchemaKind::Contract,
        "grist.citation-anchor.v1.schema.json",
        false,
        crate::core::CitationAnchor
    );
    add!(
        "citation-source-version",
        "citation-source-version",
        SchemaVersion::CITATION_SOURCE_VERSION_V1,
        SchemaKind::Contract,
        "grist.citation-source-version.v1.schema.json",
        false,
        crate::core::CitationSourceVersion
    );
    add!(
        "citation-verification",
        "citation-verification",
        SchemaVersion::CITATION_VERIFICATION_V1,
        SchemaKind::Payload,
        "grist.citation-verification.v1.schema.json",
        false,
        crate::core::CitationVerification
    );
    add!(
        "diagnostic",
        "diagnostic",
        SchemaVersion::DIAGNOSTIC_V1,
        SchemaKind::Diagnostic,
        "grist.diagnostic.v1.schema.json",
        false,
        crate::core::Diagnostic
    );
    add!(
        "text-decode",
        "text-decode",
        SchemaVersion::TEXT_DECODE_V1,
        SchemaKind::Payload,
        "grist.text-decode.v1.schema.json",
        false,
        crate::decode::DecodeReport
    );
    add!(
        "resource-budget",
        "resource-budget",
        SchemaVersion::RESOURCE_BUDGET_V1,
        SchemaKind::Options,
        "grist.resource-budget.v1.schema.json",
        false,
        crate::core::BudgetSelection
    );
    add!(
        "metric-event",
        "runtime",
        SchemaVersion::METRIC_EVENT_V1,
        SchemaKind::Event,
        "grist.metric-event.v1.schema.json",
        false,
        crate::runtime::MetricEvent
    );
    add!(
        "cache-key",
        "runtime",
        SchemaVersion::CACHE_KEY_V1,
        SchemaKind::Contract,
        "grist.cache-key.v1.schema.json",
        false,
        crate::runtime::CacheKey
    );
    add!(
        "cache-entry",
        "runtime",
        SchemaVersion::CACHE_ENTRY_V1,
        SchemaKind::Payload,
        "grist.cache-entry.v1.schema.json",
        false,
        crate::runtime::CacheEntry
    );
    add!(
        "cache-reuse",
        "runtime",
        SchemaVersion::CACHE_REUSE_V1,
        SchemaKind::Contract,
        "grist.cache-reuse.v1.schema.json",
        false,
        crate::runtime::CacheReuseRecord
    );
    add!(
        "parallelism-options",
        "runtime",
        SchemaVersion::PARALLELISM_OPTIONS_V1,
        SchemaKind::Options,
        "grist.parallelism-options.v1.schema.json",
        false,
        crate::runtime::ParallelismOptions
    );
    add!(
        "stream-event",
        "stream-event",
        SchemaVersion::STREAM_EVENT_V1,
        SchemaKind::Event,
        "grist.stream-event.v1.schema.json",
        false,
        crate::core::StreamEvent<Value>
    );
    add!(
        "batch-result",
        "batch-result",
        SchemaVersion::BATCH_RESULT_V1,
        SchemaKind::Payload,
        "grist.batch-result.v1.schema.json",
        false,
        crate::core::BatchResult<Value>
    );
    add!(
        "ingest-stream-event",
        "ingest-stream-event",
        "grist/ingest-stream-event/v1",
        SchemaKind::Event,
        "grist.ingest-stream-event.v1.schema.json",
        false,
        crate::ingest::IngestStreamEvent
    );
    add!(
        "ingest-batch-result",
        "ingest-batch-result",
        "grist/ingest-batch-result/v1",
        SchemaKind::Payload,
        "grist.ingest-batch-result.v1.schema.json",
        false,
        crate::ingest::IngestBatchResult
    );
    add!(
        "embedded-artifact",
        "embedded-artifact",
        SchemaVersion::EMBEDDED_ARTIFACT_V1,
        SchemaKind::Payload,
        "grist.embedded-artifact.v1.schema.json",
        false,
        crate::container::EmbeddedArtifact
    );
    add!(
        "container-traversal",
        "container-traversal",
        SchemaVersion::CONTAINER_TRAVERSAL_V1,
        SchemaKind::Payload,
        "grist.container-traversal.v1.schema.json",
        true,
        crate::container::ContainerTraversal
    );
    add!(
        "provider-response",
        "provider-response",
        SchemaVersion::PROVIDER_RESPONSE_V1,
        SchemaKind::Payload,
        "grist.provider-response.v1.schema.json",
        true,
        crate::provider::ProviderResponse
    );
    add!(
        "provider-request-manifest",
        "provider-request-manifest",
        SchemaVersion::PROVIDER_REQUEST_MANIFEST_V1,
        SchemaKind::Manifest,
        "grist.provider-request-manifest.v1.schema.json",
        true,
        crate::provider::ProviderRequestManifest
    );
    add!(
        "provider-recording-catalog",
        "provider-recording-catalog",
        SchemaVersion::PROVIDER_RECORDING_CATALOG_V1,
        SchemaKind::Manifest,
        "grist.provider-recording-catalog.v1.schema.json",
        true,
        crate::provider::ProviderRecordingCatalog
    );
    add!(
        "fixture-corpus-manifest",
        "fixture-corpus-manifest",
        SchemaVersion::FIXTURE_CORPUS_MANIFEST_V1,
        SchemaKind::Manifest,
        "grist.fixture-corpus-manifest.v1.schema.json",
        false,
        crate::fixtures::FixtureCorpusManifest
    );
    add!(
        "corpus-validation-report",
        "corpus-validation-report",
        SchemaVersion::CORPUS_VALIDATION_REPORT_V1,
        SchemaKind::Payload,
        "grist.corpus-validation-report.v1.schema.json",
        false,
        crate::fixtures::CorpusValidationReport
    );
    add!(
        "parser-conformance-report",
        "parser-conformance-report",
        SchemaVersion::PARSER_CONFORMANCE_REPORT_V1,
        SchemaKind::Payload,
        "grist.parser-conformance-report.v1.schema.json",
        true,
        crate::promotion::ParserConformanceReport
    );
    add!(
        "registry-snapshot",
        "registry-snapshot",
        SchemaVersion::REGISTRY_SNAPSHOT_V1,
        SchemaKind::Manifest,
        "grist.registry-snapshot.v1.schema.json",
        true,
        crate::registry::RegistrySnapshot
    );
    add!(
        "repo-ingest",
        "repo-ingest",
        SchemaVersion::REPO_INGEST_V1,
        SchemaKind::Payload,
        "grist.repo-ingest.v1.schema.json",
        true,
        crate::ingest::RepoIngestReport
    );
    add!(
        "repo-ingest-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.repo-ingest-envelope.v2.schema.json",
        true,
        crate::core::Envelope<crate::ingest::RepoIngestReport>
    );
    add!(
        "file-ingest",
        "file-ingest",
        SchemaVersion::FILE_INGEST_V1,
        SchemaKind::Payload,
        "grist.file-ingest.v1.schema.json",
        true,
        crate::ingest::FileIngestReport
    );
    add!(
        "file-ingest-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.file-ingest-envelope.v2.schema.json",
        true,
        crate::core::Envelope<crate::ingest::FileIngestReport>
    );
    add!(
        "document-graph",
        "document-graph",
        SchemaVersion::DOCUMENT_GRAPH_V2,
        SchemaKind::Graph,
        "grist.document-graph.v2.schema.json",
        true,
        crate::document_graph::DocumentGraph
    );
    add!(
        "document-graph-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.document-graph-envelope.v2.schema.json",
        true,
        crate::core::Envelope<crate::document_graph::DocumentGraph>
    );
    add!(
        "graph-transform-result",
        "graph-transform-result",
        SchemaVersion::GRAPH_TRANSFORM_RESULT_V1,
        SchemaKind::Payload,
        "grist.graph-transform-result.v1.schema.json",
        false,
        crate::transform::GraphTransformResult
    );
    add!(
        "graph-transform-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.graph-transform-envelope.v2.schema.json",
        false,
        crate::transform::GraphTransformEnvelope
    );
    add!(
        "graph-transform-source-map",
        "graph-transform-source-map",
        SchemaVersion::GRAPH_TRANSFORM_SOURCE_MAP_V1,
        SchemaKind::Contract,
        "grist.graph-transform-source-map.v1.schema.json",
        false,
        crate::transform::GraphTransformSourceMap
    );
    add!(
        "format-reconstruction-result",
        "format-reconstruction-result",
        SchemaVersion::FORMAT_RECONSTRUCTION_RESULT_V1,
        SchemaKind::Payload,
        "grist.format-reconstruction-result.v1.schema.json",
        false,
        crate::transform::ReconstructionResult
    );
    add!(
        "format-reconstruction-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.format-reconstruction-envelope.v2.schema.json",
        false,
        crate::transform::ReconstructionEnvelope
    );
    add!(
        "reconstruction-fidelity-report",
        "reconstruction-fidelity-report",
        SchemaVersion::RECONSTRUCTION_FIDELITY_REPORT_V1,
        SchemaKind::Contract,
        "grist.reconstruction-fidelity-report.v1.schema.json",
        false,
        crate::transform::ReconstructionFidelityReport
    );
    add!(
        "segment",
        "segment",
        SchemaVersion::SEGMENT_V1,
        SchemaKind::Segment,
        "grist.segment.v1.schema.json",
        false,
        crate::segment::Segment
    );
    add!(
        "segment-collection",
        "segment-collection",
        SchemaVersion::SEGMENT_COLLECTION_V1,
        SchemaKind::Payload,
        "grist.segment-collection.v1.schema.json",
        false,
        crate::segment::SegmentCollection
    );
    add!(
        "segment-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.segment-envelope.v2.schema.json",
        false,
        crate::core::Envelope<crate::segment::SegmentCollection>
    );
    add!(
        "segment-event",
        "segment-event",
        SchemaVersion::SEGMENT_EVENT_V1,
        SchemaKind::Event,
        "grist.segment-event.v1.schema.json",
        false,
        crate::segment::SegmentEvent
    );
    add!(
        "rendered-summary",
        "rendered-summary",
        SchemaVersion::RENDERED_SUMMARY_V1,
        SchemaKind::Payload,
        "grist.rendered-summary.v1.schema.json",
        false,
        crate::summary::RenderedSummary
    );
    add!(
        "render-result",
        "render-result",
        SchemaVersion::RENDER_RESULT_V1,
        SchemaKind::Payload,
        "grist.render-result.v1.schema.json",
        false,
        crate::render::RenderResult
    );
    add!(
        "render-source-map",
        "render-source-map",
        SchemaVersion::RENDER_SOURCE_MAP_V1,
        SchemaKind::Contract,
        "grist.render-source-map.v1.schema.json",
        false,
        crate::render::RenderSourceMap
    );
    add!(
        "text",
        "text",
        SchemaVersion::TEXT_V2,
        SchemaKind::Payload,
        "grist.text.v2.schema.json",
        false,
        crate::text::TextDocument
    );
    add!(
        "text-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.text-envelope.v2.schema.json",
        false,
        crate::core::Envelope<crate::text::TextDocument>
    );

    add!(
        "parse-options",
        "parse-options",
        "grist/parse-options/v1",
        SchemaKind::Options,
        "grist.parse-options.v1.schema.json",
        false,
        crate::core::ParseOptions
    );
    add!(
        "auto-format-options",
        "auto-format-options",
        "grist/auto-format-options/v1",
        SchemaKind::Options,
        "grist.auto-format-options.v1.schema.json",
        false,
        crate::core::AutoFormatOptions
    );
    add!(
        "source-options",
        "source-options",
        "grist/source-options/v1",
        SchemaKind::Options,
        "grist.source-options.v1.schema.json",
        false,
        crate::core::SourceOptions
    );
    add!(
        "diagnostic-options",
        "diagnostic-options",
        "grist/diagnostic-options/v1",
        SchemaKind::Options,
        "grist.diagnostic-options.v1.schema.json",
        false,
        crate::core::DiagnosticOptions
    );
    add!(
        "schema-options",
        "schema-options",
        "grist/schema-options/v1",
        SchemaKind::Options,
        "grist.schema-options.v1.schema.json",
        false,
        crate::core::SchemaOptions
    );
    add!(
        "legacy-limits-options",
        "legacy-limits-options",
        "grist/legacy-limits-options/v1",
        SchemaKind::Options,
        "grist.legacy-limits-options.v1.schema.json",
        false,
        crate::core::Limits
    );
    add!(
        "detection-options",
        "detection-options",
        "grist/detection-options/v1",
        SchemaKind::Options,
        "grist.detection-options.v1.schema.json",
        false,
        crate::detect::DetectionOptions
    );
    add!(
        "decode-options",
        "decode-options",
        "grist/decode-options/v1",
        SchemaKind::Options,
        "grist.decode-options.v1.schema.json",
        false,
        crate::decode::DecodeOptions
    );
    add!(
        "citation-anchor-options",
        "citation-anchor-options",
        "grist/citation-anchor-options/v1",
        SchemaKind::Options,
        "grist.citation-anchor-options.v1.schema.json",
        false,
        crate::core::CitationAnchorOptions
    );
    add!(
        "citation-verification-options",
        "citation-verification-options",
        "grist/citation-verification-options/v1",
        SchemaKind::Options,
        "grist.citation-verification-options.v1.schema.json",
        false,
        crate::core::CitationVerificationOptions
    );
    add!(
        "artifact-capture-options",
        "artifact-capture-options",
        "grist/artifact-capture-options/v1",
        SchemaKind::Options,
        "grist.artifact-capture-options.v1.schema.json",
        false,
        crate::container::ArtifactCaptureOptions
    );
    add!(
        "container-parse-options",
        "container-parse-options",
        "grist/container-parse-options/v1",
        SchemaKind::Options,
        "grist.container-parse-options.v1.schema.json",
        false,
        crate::container::ContainerParseOptions
    );
    add!(
        "file-ingest-options",
        "file-ingest-options",
        "grist/file-ingest-options/v1",
        SchemaKind::Options,
        "grist.file-ingest-options.v1.schema.json",
        false,
        crate::ingest::FileIngestOptions
    );
    add!(
        "repo-ingest-options",
        "repo-ingest-options",
        "grist/repo-ingest-options/v1",
        SchemaKind::Options,
        "grist.repo-ingest-options.v1.schema.json",
        false,
        crate::ingest::RepoIngestOptions
    );
    add!(
        "segment-options",
        "segment-options",
        SchemaVersion::SEGMENT_OPTIONS_V1,
        SchemaKind::Options,
        "grist.segment-options.v1.schema.json",
        false,
        crate::segment::SegmentOptions
    );
    add!(
        "transform-options",
        "transform-options",
        "grist/transform-options/v1",
        SchemaKind::Options,
        "grist.transform-options.v1.schema.json",
        false,
        crate::document_graph::TransformOptions
    );
    add!(
        "graph-transform-options",
        "graph-transform-options",
        SchemaVersion::GRAPH_TRANSFORM_OPTIONS_V1,
        SchemaKind::Options,
        "grist.graph-transform-options.v1.schema.json",
        false,
        crate::transform::GraphTransformOptions
    );
    add!(
        "reconstruction-options",
        "reconstruction-options",
        SchemaVersion::RECONSTRUCTION_OPTIONS_V1,
        SchemaKind::Options,
        "grist.reconstruction-options.v1.schema.json",
        false,
        crate::transform::ReconstructionOptions
    );
    add!(
        "render-options",
        "render-options",
        SchemaVersion::RENDER_OPTIONS_V1,
        SchemaKind::Options,
        "grist.render-options.v1.schema.json",
        false,
        crate::render::RenderOptions
    );
    add!(
        "summary-options",
        "summary-options",
        "grist/summary-options/v1",
        SchemaKind::Options,
        "grist.summary-options.v1.schema.json",
        false,
        crate::summary::SummaryOptions
    );
    add!(
        "text-options",
        "text-options",
        "grist/text-options/v1",
        SchemaKind::Options,
        "grist.text-options.v1.schema.json",
        false,
        crate::text::TextOptions
    );
    add!(
        "security-policy",
        "security-policy",
        "grist/security-policy/v1",
        SchemaKind::Options,
        "grist.security-policy.v1.schema.json",
        false,
        crate::security::SecurityPolicy
    );
    add!(
        "archive-security-options",
        "archive-security-options",
        "grist/archive-security-options/v1",
        SchemaKind::Options,
        "grist.archive-security-options.v1.schema.json",
        false,
        crate::security::ArchiveSecurityPolicy
    );
    add!(
        "ocr-options",
        "ocr-options",
        "grist/ocr-options/v1",
        SchemaKind::Options,
        "grist.ocr-options.v1.schema.json",
        true,
        crate::provider::OcrOptions
    );
    add!(
        "transcription-options",
        "transcription-options",
        "grist/transcription-options/v1",
        SchemaKind::Options,
        "grist.transcription-options.v1.schema.json",
        true,
        crate::provider::TranscriptionOptions
    );
    add!(
        "decryption-options",
        "decryption-options",
        "grist/decryption-options/v1",
        SchemaKind::Options,
        "grist.decryption-options.v1.schema.json",
        true,
        crate::provider::DecryptionOptions
    );
    add!(
        "isolated-backend-options",
        "isolated-backend-options",
        "grist/isolated-backend-options/v1",
        SchemaKind::Options,
        "grist.isolated-backend-options.v1.schema.json",
        true,
        crate::provider::IsolatedBackendOptions
    );

    add!(
        "schema-catalog",
        "schema-catalog",
        SchemaVersion::SCHEMA_CATALOG_V1,
        SchemaKind::Manifest,
        "grist.schema-catalog.v1.schema.json",
        false,
        SchemaCatalog
    );
    add!(
        "schema-validation",
        "schema-validation",
        SchemaVersion::SCHEMA_VALIDATION_V1,
        SchemaKind::Payload,
        "grist.schema-validation.v1.schema.json",
        false,
        SchemaValidationReport
    );
    add!(
        "migration-manifest",
        "migration-manifest",
        SchemaVersion::SCHEMA_MIGRATION_MANIFEST_V1,
        SchemaKind::Manifest,
        "grist.schema-migration-manifest.v1.schema.json",
        false,
        MigrationManifest
    );
    add!(
        "canonical-examples",
        "canonical-examples",
        SchemaVersion::CANONICAL_EXAMPLES_V1,
        SchemaKind::Manifest,
        "grist.canonical-examples.v1.schema.json",
        false,
        CanonicalExampleManifest
    );
    add!(
        "backend-output-manifest",
        "backend-output-manifest",
        SchemaVersion::BACKEND_OUTPUT_MANIFEST_V1,
        SchemaKind::Manifest,
        "grist.backend-output-manifest.v1.schema.json",
        true,
        BackendOutputManifest
    );
    add!(
        "capability-manifest",
        "capability-manifest",
        SchemaVersion::CAPABILITY_MANIFEST_V1,
        SchemaKind::Manifest,
        "grist.capability-manifest.v1.schema.json",
        false,
        crate::capabilities::CapabilityManifest
    );
    #[cfg(feature = "cli")]
    {
        add!(
            "cli-detection-report",
            "cli",
            SchemaVersion::CLI_DETECTION_REPORT_V1,
            SchemaKind::Payload,
            "grist.cli-detection-report.v1.schema.json",
            false,
            crate::cli::DetectionReport
        );
        add!(
            "cli-text-output-manifest",
            "cli",
            SchemaVersion::CLI_TEXT_OUTPUT_MANIFEST_V1,
            SchemaKind::Manifest,
            "grist.cli-text-output-manifest.v1.schema.json",
            false,
            crate::cli::TextOutputManifest
        );
    }
    add!(
        "compatibility-policy",
        "compatibility-policy",
        "grist/compatibility-policy/v1",
        SchemaKind::Options,
        "grist.compatibility-policy.v1.schema.json",
        false,
        CompatibilityPolicy
    );
    add!(
        "compatibility-report",
        "compatibility-report",
        "grist/compatibility-report/v1",
        SchemaKind::Payload,
        "grist.compatibility-report.v1.schema.json",
        false,
        CompatibilityReport
    );
    add!(
        "unknown-enum-document",
        "unknown-enum-document",
        "grist/unknown-enum-document/v1",
        SchemaKind::Payload,
        "grist.unknown-enum-document.v1.schema.json",
        false,
        UnknownEnumDocument
    );

    #[cfg(feature = "serialization")]
    {
        add!(
            "serialization",
            "serialization",
            SchemaVersion::STRUCTURED_TEXT_V2,
            SchemaKind::Payload,
            "grist.structured-text.v2.schema.json",
            true,
            crate::serialization::SerializationPayload
        );
        add!(
            "serialization-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.serialization-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::serialization::SerializationPayload>
        );
        add!(
            "serialization-options",
            "serialization-options",
            "grist/structured-text-options/v2",
            SchemaKind::Options,
            "grist.structured-text-options.v2.schema.json",
            false,
            crate::serialization::SerializationOptions
        );
    }
    #[cfg(feature = "model-output")]
    {
        add!(
            "model-output",
            "model-output",
            SchemaVersion::MODEL_OUTPUT_V1,
            SchemaKind::Payload,
            "grist.model-output.v1.schema.json",
            true,
            crate::model_output::ModelOutputReport
        );
        add!(
            "model-output-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.model-output-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::model_output::ModelOutputReport>
        );
        add!(
            "model-output-event",
            "model-output-event",
            "grist/model-output-event/v1",
            SchemaKind::Event,
            "grist.model-output-event.v1.schema.json",
            false,
            crate::model_output::ModelOutputEvent
        );
        add!(
            "model-output-event-v2",
            "model-output-event",
            "grist/model-output-event/v2",
            SchemaKind::Event,
            "grist.model-output-event.v2.schema.json",
            true,
            crate::model_output::ModelOutputStreamEventV2
        );
        add!(
            "model-output-options",
            "model-output-options",
            "grist/model-output-options/v1",
            SchemaKind::Options,
            "grist.model-output-options.v1.schema.json",
            false,
            crate::model_output::ModelOutputOptions
        );
    }
    #[cfg(feature = "markdown")]
    {
        add!(
            "markdown",
            "markdown",
            SchemaVersion::MARKDOWN_V2,
            SchemaKind::Payload,
            "grist.markdown.v2.schema.json",
            true,
            crate::markdown::MarkdownDocument
        );
        add!(
            "markdown-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.markdown-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::markdown::MarkdownDocument>
        );
        add!(
            "markdown-options",
            "markdown-options",
            "grist/markdown-options/v1",
            SchemaKind::Options,
            "grist.markdown-options.v1.schema.json",
            false,
            crate::markdown::MarkdownOptions
        );
    }
    #[cfg(feature = "notebooks")]
    {
        add!(
            "r_markdown",
            "r_markdown",
            SchemaVersion::MARKDOWN_V2,
            SchemaKind::Payload,
            "grist.r-markdown.v2.schema.json",
            true,
            crate::markdown::MarkdownDocument
        );
        add!(
            "quarto",
            "quarto",
            SchemaVersion::MARKDOWN_V2,
            SchemaKind::Payload,
            "grist.quarto.v2.schema.json",
            true,
            crate::markdown::MarkdownDocument
        );
        add!(
            "r_markdown-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.r-markdown-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::markdown::MarkdownDocument>
        );
        add!(
            "quarto-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.quarto-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::markdown::MarkdownDocument>
        );
        add!(
            "r_markdown-options",
            "r-markdown-options",
            "grist/r-markdown-options/v1",
            SchemaKind::Options,
            "grist.r-markdown-options.v1.schema.json",
            false,
            crate::markdown::MarkdownOptions
        );
        add!(
            "quarto-options",
            "quarto-options",
            "grist/quarto-options/v1",
            SchemaKind::Options,
            "grist.quarto-options.v1.schema.json",
            false,
            crate::markdown::MarkdownOptions
        );
    }
    #[cfg(feature = "restructured-text")]
    {
        add!(
            "restructured-text",
            "restructured-text",
            SchemaVersion::RESTRUCTURED_TEXT_V1,
            SchemaKind::Payload,
            "grist.restructured-text.v1.schema.json",
            true,
            crate::restructured_text::RestructuredTextDocument
        );
        add!(
            "restructured-text-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.restructured-text-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::restructured_text::RestructuredTextDocument>
        );
        add!(
            "restructured-text-options",
            "restructured-text-options",
            "grist/restructured-text-options/v1",
            SchemaKind::Options,
            "grist.restructured-text-options.v1.schema.json",
            false,
            crate::restructured_text::RestructuredTextOptions
        );
    }
    #[cfg(feature = "asciidoc")]
    {
        add!(
            "asciidoc",
            "asciidoc",
            SchemaVersion::ASCIIDOC_V1,
            SchemaKind::Payload,
            "grist.asciidoc.v1.schema.json",
            true,
            crate::asciidoc::AsciiDocDocument
        );
        add!(
            "asciidoc-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.asciidoc-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::asciidoc::AsciiDocDocument>
        );
        add!(
            "asciidoc-options",
            "asciidoc-options",
            "grist/asciidoc-options/v1",
            SchemaKind::Options,
            "grist.asciidoc-options.v1.schema.json",
            false,
            crate::asciidoc::AsciiDocOptions
        );
    }
    #[cfg(feature = "ldgr-projection")]
    {
        add!(
            "ldgr-projection",
            "ldgr-projection",
            SchemaVersion::LDGR_PROJECTION_V1,
            SchemaKind::Payload,
            "grist.ldgr-projection.v1.schema.json",
            true,
            crate::ldgr_projection::LdgrProjectionDocument
        );
        add!(
            "ldgr-projection-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.ldgr-projection-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::ldgr_projection::LdgrProjectionDocument>
        );
        add!(
            "ldgr-projection-options",
            "ldgr-projection-options",
            "grist/ldgr-projection-options/v1",
            SchemaKind::Options,
            "grist.ldgr-projection-options.v1.schema.json",
            false,
            crate::ldgr_projection::LdgrProjectionOptions
        );
        add!(
            "ldgr-projection-validation-options",
            "ldgr-projection-validation-options",
            "grist/ldgr-projection-validation-options/v1",
            SchemaKind::Options,
            "grist.ldgr-projection-validation-options.v1.schema.json",
            false,
            crate::ldgr_projection::LdgrProjectionValidationOptions
        );
        add!(
            "ldgr-projection-render-options",
            "ldgr-projection-render-options",
            "grist/ldgr-projection-render-options/v1",
            SchemaKind::Options,
            "grist.ldgr-projection-render-options.v1.schema.json",
            false,
            crate::ldgr_projection::LdgrProjectionRenderOptions
        );
    }
    #[cfg(feature = "html")]
    {
        add!(
            "html",
            "html",
            SchemaVersion::HTML_V2,
            SchemaKind::Payload,
            "grist.html.v2.schema.json",
            true,
            crate::html::HtmlDocument
        );
        add!(
            "html-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.html-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::html::HtmlDocument>
        );
        add!(
            "html-options",
            "html-options",
            "grist/html-options/v1",
            SchemaKind::Options,
            "grist.html-options.v1.schema.json",
            false,
            crate::html::HtmlOptions
        );
    }
    #[cfg(feature = "archives")]
    {
        add!(
            "archive",
            "archive",
            SchemaVersion::ARCHIVE_V1,
            SchemaKind::Payload,
            "grist.archive.v1.schema.json",
            true,
            crate::archive::ArchiveDocument
        );
        add!(
            "archive-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.archive-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::archive::ArchiveDocument>
        );
        add!(
            "archive-options",
            "archive-options",
            "grist/archive-options/v1",
            SchemaKind::Options,
            "grist.archive-options.v1.schema.json",
            false,
            crate::archive::ArchiveOptions
        );
    }

    #[cfg(feature = "epub")]
    {
        add!(
            "epub",
            "epub",
            SchemaVersion::EPUB_V1,
            SchemaKind::Payload,
            "grist.epub.v1.schema.json",
            true,
            crate::epub::EpubDocument
        );
        add!(
            "epub-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.epub-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::epub::EpubDocument>
        );
        add!(
            "epub-options",
            "epub-options",
            "grist/epub-options/v1",
            SchemaKind::Options,
            "grist.epub-options.v1.schema.json",
            false,
            crate::epub::EpubOptions
        );
    }
    #[cfg(feature = "pdf")]
    {
        add!(
            "pdf",
            "pdf",
            SchemaVersion::PDF_V1,
            SchemaKind::Payload,
            "grist.pdf.v1.schema.json",
            true,
            crate::pdf::PdfDocument
        );
        add!(
            "pdf-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.pdf-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::pdf::PdfDocument>
        );
        add!(
            "pdf-options",
            "pdf-options",
            "grist/pdf-options/v1",
            SchemaKind::Options,
            "grist.pdf-options.v1.schema.json",
            false,
            crate::pdf::PdfOptions
        );
    }
    #[cfg(feature = "media")]
    {
        add!(
            "image",
            "image",
            SchemaVersion::IMAGE_V1,
            SchemaKind::Payload,
            "grist.image.v1.schema.json",
            false,
            crate::image::ImageDocument
        );
        add!(
            "image-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.image-envelope.v2.schema.json",
            false,
            crate::core::Envelope<crate::image::ImageDocument>
        );
        add!(
            "image-options",
            "image-options",
            "grist/image-options/v1",
            SchemaKind::Options,
            "grist.image-options.v1.schema.json",
            false,
            crate::image::ImageOptions
        );
        add!(
            "subtitle",
            "media",
            SchemaVersion::SUBTITLE_V1,
            SchemaKind::Payload,
            "grist.subtitle.v1.schema.json",
            false,
            crate::subtitle::SubtitleDocument
        );
        add!(
            "subtitle-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.subtitle-envelope.v2.schema.json",
            false,
            crate::core::Envelope<crate::subtitle::SubtitleDocument>
        );
        add!(
            "subtitle-options",
            "subtitle-options",
            "grist/subtitle-options/v1",
            SchemaKind::Options,
            "grist.subtitle-options.v1.schema.json",
            false,
            crate::subtitle::SubtitleOptions
        );
    }
    #[cfg(feature = "word-ooxml")]
    {
        add!(
            "word-ooxml",
            "word-ooxml",
            SchemaVersion::WORD_OOXML_V1,
            SchemaKind::Payload,
            "grist.word-ooxml.v1.schema.json",
            true,
            crate::word_ooxml::WordOoxmlDocument
        );
        add!(
            "word-ooxml-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.word-ooxml-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::word_ooxml::WordOoxmlDocument>
        );
        add!(
            "word-ooxml-options",
            "word-ooxml-options",
            "grist/word-ooxml-options/v1",
            SchemaKind::Options,
            "grist.word-ooxml-options.v1.schema.json",
            false,
            crate::word_ooxml::WordOoxmlOptions
        );
    }
    #[cfg(feature = "structured-binary")]
    #[cfg(feature = "columnar")]
    {
        add!(
            "columnar",
            "columnar",
            SchemaVersion::COLUMNAR_V1,
            SchemaKind::Payload,
            "grist.columnar.v1.schema.json",
            true,
            crate::columnar::ColumnarDocument
        );
        add!(
            "columnar-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.columnar-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::columnar::ColumnarDocument>
        );
        add!(
            "columnar-options",
            "columnar-options",
            "grist/columnar-options/v1",
            SchemaKind::Options,
            "grist.columnar-options.v1.schema.json",
            false,
            crate::columnar::ColumnarOptions
        );
        add!(
            "columnar-stream-event",
            "columnar",
            "grist/columnar-stream-event/v1",
            SchemaKind::Event,
            "grist.columnar-stream-event.v1.schema.json",
            true,
            crate::columnar::ColumnarStreamEvent
        );
    }
    #[cfg(feature = "structured-binary")]
    {
        add!(
            "structured-binary",
            "structured-binary",
            SchemaVersion::STRUCTURED_BINARY_V1,
            SchemaKind::Payload,
            "grist.structured-binary.v1.schema.json",
            true,
            crate::structured_binary::StructuredBinaryDocument
        );
        add!(
            "structured-binary-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.structured-binary-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::structured_binary::StructuredBinaryDocument>
        );
        add!(
            "structured-binary-options",
            "structured-binary-options",
            "grist/structured-binary-options/v1",
            SchemaKind::Options,
            "grist.structured-binary-options.v1.schema.json",
            false,
            crate::structured_binary::StructuredBinaryOptions
        );
    }
    #[cfg(feature = "sqlite")]
    {
        add!(
            "sqlite",
            "sqlite",
            SchemaVersion::SQLITE_V1,
            SchemaKind::Payload,
            "grist.sqlite.v1.schema.json",
            true,
            crate::sqlite::SqliteDocument
        );
        add!(
            "sqlite-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.sqlite-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::sqlite::SqliteDocument>
        );
        add!(
            "sqlite-options",
            "sqlite-options",
            "grist/sqlite-options/v1",
            SchemaKind::Options,
            "grist.sqlite-options.v1.schema.json",
            false,
            crate::sqlite::SqliteOptions
        );
    }
    #[cfg(feature = "notebooks")]
    {
        add!(
            "ipynb",
            "notebooks",
            SchemaVersion::IPYNB_V1,
            SchemaKind::Payload,
            "grist.ipynb.v1.schema.json",
            true,
            crate::notebook::NotebookDocument
        );
        add!(
            "ipynb-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.ipynb-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::notebook::NotebookDocument>
        );
        add!(
            "ipynb-options",
            "ipynb-options",
            "grist/ipynb-options/v1",
            SchemaKind::Options,
            "grist.ipynb-options.v1.schema.json",
            false,
            crate::notebook::NotebookOptions
        );
    }
    #[cfg(feature = "email-message")]
    {
        add!(
            "email",
            "email-message",
            SchemaVersion::EMAIL_V1,
            SchemaKind::Payload,
            "grist.email.v1.schema.json",
            true,
            crate::email::EmailDocument
        );
        add!(
            "email-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.email-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::email::EmailDocument>
        );
        add!(
            "email-options",
            "email-options",
            "grist/email-options/v1",
            SchemaKind::Options,
            "grist.email-options.v1.schema.json",
            false,
            crate::email::EmailOptions
        );
        add!(
            "mbox",
            "email-message",
            SchemaVersion::MBOX_V1,
            SchemaKind::Payload,
            "grist.mbox.v1.schema.json",
            true,
            crate::mbox::MboxDocument
        );
        add!(
            "mbox-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.mbox-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::mbox::MboxDocument>
        );
        add!(
            "mbox-options",
            "mbox-options",
            "grist/mbox-options/v1",
            SchemaKind::Options,
            "grist.mbox-options.v1.schema.json",
            false,
            crate::mbox::MboxOptions
        );
        add!(
            "outlook-msg",
            "email-message",
            SchemaVersion::OUTLOOK_MSG_V1,
            SchemaKind::Payload,
            "grist.outlook-msg.v1.schema.json",
            true,
            crate::outlook::OutlookMsgDocument
        );
        add!(
            "outlook-msg-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.outlook-msg-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::outlook::OutlookMsgDocument>
        );
        add!(
            "outlook-msg-options",
            "outlook-msg-options",
            "grist/outlook-msg-options/v1",
            SchemaKind::Options,
            "grist.outlook-msg-options.v1.schema.json",
            false,
            crate::outlook::OutlookMsgOptions
        );
        add!(
            "icalendar",
            "email-message",
            SchemaVersion::ICALENDAR_V1,
            SchemaKind::Payload,
            "grist.icalendar.v1.schema.json",
            true,
            crate::calendar_contact::ICalendarDocument
        );
        add!(
            "icalendar-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.icalendar-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::calendar_contact::ICalendarDocument>
        );
        add!(
            "icalendar-options",
            "icalendar-options",
            "grist/icalendar-options/v1",
            SchemaKind::Options,
            "grist.icalendar-options.v1.schema.json",
            false,
            crate::calendar_contact::ICalendarOptions
        );
        add!(
            "vcard",
            "email-message",
            SchemaVersion::VCARD_V1,
            SchemaKind::Payload,
            "grist.vcard.v1.schema.json",
            true,
            crate::calendar_contact::VCardDocument
        );
        add!(
            "vcard-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.vcard-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::calendar_contact::VCardDocument>
        );
        add!(
            "vcard-options",
            "vcard-options",
            "grist/vcard-options/v1",
            SchemaKind::Options,
            "grist.vcard-options.v1.schema.json",
            false,
            crate::calendar_contact::VCardOptions
        );
        add!(
            "mbox-stream-event",
            "stream-event",
            "grist/mbox-stream-event/v1",
            SchemaKind::Event,
            "grist.mbox-stream-event.v1.schema.json",
            true,
            crate::mbox::MboxStreamEvent
        );
    }
    #[cfg(feature = "presentation-ooxml")]
    {
        add!(
            "presentation-ooxml",
            "presentation-ooxml",
            SchemaVersion::PRESENTATION_OOXML_V1,
            SchemaKind::Payload,
            "grist.presentation-ooxml.v1.schema.json",
            true,
            crate::presentation_ooxml::PresentationOoxmlDocument
        );
        add!(
            "presentation-ooxml-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.presentation-ooxml-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::presentation_ooxml::PresentationOoxmlDocument>
        );
        add!(
            "presentation-ooxml-options",
            "presentation-ooxml-options",
            "grist/presentation-ooxml-options/v1",
            SchemaKind::Options,
            "grist.presentation-ooxml-options.v1.schema.json",
            false,
            crate::presentation_ooxml::PresentationOoxmlOptions
        );
    }
    #[cfg(feature = "presentation-odf")]
    {
        add!(
            "presentation-odf",
            "presentation-odf",
            SchemaVersion::PRESENTATION_ODF_V1,
            SchemaKind::Payload,
            "grist.presentation-odf.v1.schema.json",
            true,
            crate::presentation_odf::OdfPresentationDocument
        );
        add!(
            "presentation-odf-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.presentation-odf-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::presentation_odf::OdfPresentationDocument>
        );
        add!(
            "presentation-odf-options",
            "presentation-odf-options",
            "grist/presentation-odf-options/v1",
            SchemaKind::Options,
            "grist.presentation-odf-options.v1.schema.json",
            false,
            crate::presentation_odf::OdfPresentationOptions
        );
    }
    #[cfg(feature = "spreadsheet-ooxml")]
    {
        add!(
            "spreadsheet-ooxml",
            "spreadsheet-ooxml",
            SchemaVersion::SPREADSHEET_OOXML_V1,
            SchemaKind::Payload,
            "grist.spreadsheet-ooxml.v1.schema.json",
            true,
            crate::spreadsheet_ooxml::SpreadsheetOoxmlDocument
        );
        add!(
            "spreadsheet-ooxml-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.spreadsheet-ooxml-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::spreadsheet_ooxml::SpreadsheetOoxmlDocument>
        );
        add!(
            "spreadsheet-ooxml-options",
            "spreadsheet-ooxml-options",
            "grist/spreadsheet-ooxml-options/v1",
            SchemaKind::Options,
            "grist.spreadsheet-ooxml-options.v1.schema.json",
            false,
            crate::spreadsheet_ooxml::SpreadsheetOoxmlOptions
        );
    }
    #[cfg(feature = "spreadsheet-odf")]
    {
        add!(
            "spreadsheet-odf",
            "spreadsheet-odf",
            SchemaVersion::SPREADSHEET_ODF_V1,
            SchemaKind::Payload,
            "grist.spreadsheet-odf.v1.schema.json",
            true,
            crate::spreadsheet_odf::SpreadsheetOdfDocument
        );
        add!(
            "spreadsheet-odf-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.spreadsheet-odf-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::spreadsheet_odf::SpreadsheetOdfDocument>
        );
        add!(
            "spreadsheet-odf-options",
            "spreadsheet-odf-options",
            "grist/spreadsheet-odf-options/v1",
            SchemaKind::Options,
            "grist.spreadsheet-odf-options.v1.schema.json",
            false,
            crate::spreadsheet_odf::SpreadsheetOdfOptions
        );
    }
    #[cfg(feature = "odf-word")]
    {
        add!(
            "odf-word",
            "odf-word",
            SchemaVersion::ODF_WORD_V1,
            SchemaKind::Payload,
            "grist.odf-word.v1.schema.json",
            true,
            crate::odf_word::OdfWordDocument
        );
        add!(
            "odf-word-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.odf-word-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::odf_word::OdfWordDocument>
        );
        add!(
            "odf-word-options",
            "odf-word-options",
            "grist/odf-word-options/v1",
            SchemaKind::Options,
            "grist.odf-word-options.v1.schema.json",
            false,
            crate::odf_word::OdfWordOptions
        );
    }
    #[cfg(feature = "rtf")]
    {
        add!(
            "rtf",
            "rtf",
            SchemaVersion::RTF_V1,
            SchemaKind::Payload,
            "grist.rtf.v1.schema.json",
            true,
            crate::rtf::RtfDocument
        );
        add!(
            "rtf-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.rtf-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::rtf::RtfDocument>
        );
        add!(
            "rtf-options",
            "rtf-options",
            "grist/rtf-options/v1",
            SchemaKind::Options,
            "grist.rtf-options.v1.schema.json",
            false,
            crate::rtf::RtfOptions
        );
    }
    #[cfg(feature = "xml")]
    {
        add!(
            "xml",
            "xml",
            SchemaVersion::XML_V1,
            SchemaKind::Payload,
            "grist.xml.v1.schema.json",
            true,
            crate::xml::XmlDocument
        );
        add!(
            "xml-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.xml-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::xml::XmlDocument>
        );
        add!(
            "xml-options",
            "xml-options",
            "grist/xml-options/v1",
            SchemaKind::Options,
            "grist.xml-options.v1.schema.json",
            false,
            crate::xml::XmlOptions
        );
    }
    #[cfg(feature = "csv")]
    {
        add!(
            "csv",
            "csv",
            SchemaVersion::CSV_V2,
            SchemaKind::Payload,
            "grist.csv.v2.schema.json",
            true,
            crate::csv::CsvDocument
        );
        add!(
            "csv-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.csv-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::csv::CsvDocument>
        );
        add!(
            "csv-options",
            "csv-options",
            "grist/csv-options/v2",
            SchemaKind::Options,
            "grist.csv-options.v2.schema.json",
            false,
            crate::csv::CsvOptions
        );
    }

    add!(
        "code",
        "code",
        SchemaVersion::CODE_V1,
        SchemaKind::Payload,
        "grist.code.v1.schema.json",
        true,
        crate::code::CodeFile
    );
    add!(
        "code-envelope",
        "envelope",
        SchemaVersion::ENVELOPE_V2,
        SchemaKind::Envelope,
        "grist.code-envelope.v2.schema.json",
        true,
        crate::core::Envelope<crate::code::CodeFile>
    );
    #[cfg(feature = "manifests")]
    add!(
        "manifest",
        "manifest",
        SchemaVersion::MANIFEST_V1,
        SchemaKind::Payload,
        "grist.manifest.v1.schema.json",
        false,
        crate::manifests::ManifestDocument
    );
    #[cfg(feature = "manifests")]
    add!(
        "manifest-options",
        "manifest",
        crate::manifests::MANIFEST_OPTIONS_SCHEMA_V1,
        SchemaKind::Options,
        "grist.manifest-options.v1.schema.json",
        false,
        crate::manifests::ManifestOptions
    );
    add!(
        "code-options",
        "code-options",
        crate::code::CODE_OPTIONS_SCHEMA_V1,
        SchemaKind::Options,
        "grist.code-options.v1.schema.json",
        false,
        crate::code::CodeIngestOptions
    );
    add!(
        "tree-sitter-language-adapter",
        "code",
        crate::code::TREE_SITTER_ADAPTER_SCHEMA_V1,
        SchemaKind::Contract,
        "grist.tree-sitter-language-adapter.v1.schema.json",
        false,
        crate::code::TreeSitterAdapterMetadata
    );
    #[cfg(feature = "rust")]
    {
        add!(
            "rust-code",
            "rust-code",
            SchemaVersion::RUST_CODE_V1,
            SchemaKind::Payload,
            "grist.rust-code.v1.schema.json",
            true,
            crate::rust::RustFile
        );
        add!(
            "rust-code-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.rust-code-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::rust::RustFile>
        );
        add!(
            "rust-code-options",
            "rust-code-options",
            "grist/rust-code-options/v1",
            SchemaKind::Options,
            "grist.rust-code-options.v1.schema.json",
            false,
            crate::rust::RustIngestOptions
        );
    }
    #[cfg(feature = "python")]
    {
        add!(
            "python-code",
            "python-code",
            SchemaVersion::PYTHON_CODE_V1,
            SchemaKind::Payload,
            "grist.python-code.v1.schema.json",
            true,
            crate::python::PythonFile
        );
        add!(
            "python-code-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.python-code-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::python::PythonFile>
        );
        add!(
            "python-code-options",
            "python-code-options",
            "grist/python-code-options/v1",
            SchemaKind::Options,
            "grist.python-code-options.v1.schema.json",
            false,
            crate::python::PythonIngestOptions
        );
    }
    #[cfg(feature = "typescript")]
    {
        add!(
            "typescript-code",
            "typescript-code",
            SchemaVersion::TYPESCRIPT_CODE_V1,
            SchemaKind::Payload,
            "grist.typescript-code.v1.schema.json",
            true,
            crate::typescript::TypeScriptFile
        );
        add!(
            "typescript-code-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.typescript-code-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::typescript::TypeScriptFile>
        );
        add!(
            "typescript-code-options",
            "typescript-code-options",
            "grist/typescript-code-options/v1",
            SchemaKind::Options,
            "grist.typescript-code-options.v1.schema.json",
            false,
            crate::typescript::TypeScriptIngestOptions
        );
    }
    #[cfg(feature = "javascript")]
    {
        add!(
            "javascript-code",
            "javascript-code",
            SchemaVersion::JAVASCRIPT_CODE_V1,
            SchemaKind::Payload,
            "grist.javascript-code.v1.schema.json",
            true,
            crate::javascript::JavaScriptFile
        );
        add!(
            "javascript-code-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.javascript-code-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::javascript::JavaScriptFile>
        );
        add!(
            "javascript-code-options",
            "javascript-code-options",
            "grist/javascript-code-options/v1",
            SchemaKind::Options,
            "grist.javascript-code-options.v1.schema.json",
            false,
            crate::javascript::JavaScriptIngestOptions
        );
    }
    #[cfg(feature = "latex")]
    {
        add!(
            "latex",
            "latex",
            SchemaVersion::LATEX_V1,
            SchemaKind::Payload,
            "grist.latex.v1.schema.json",
            true,
            crate::latex::LatexDocument
        );
        add!(
            "latex-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.latex-envelope.v2.schema.json",
            true,
            crate::core::Envelope<crate::latex::LatexDocument>
        );
        add!(
            "latex-options",
            "latex-options",
            "grist/latex-options/v1",
            SchemaKind::Options,
            "grist.latex-options.v1.schema.json",
            false,
            crate::latex::LatexOptions
        );
    }
    #[cfg(feature = "bibliography")]
    {
        add!(
            "bibliography",
            "bibliography",
            SchemaVersion::BIBLIOGRAPHY_V1,
            SchemaKind::Payload,
            "grist.bibliography.v1.schema.json",
            false,
            crate::bibliography::BibliographyDocument
        );
        add!(
            "bibliography-envelope",
            "envelope",
            SchemaVersion::ENVELOPE_V2,
            SchemaKind::Envelope,
            "grist.bibliography-envelope.v2.schema.json",
            false,
            crate::core::Envelope<crate::bibliography::BibliographyDocument>
        );
        add!(
            "bibliography-options",
            "bibliography-options",
            "grist/bibliography-options/v1",
            SchemaKind::Options,
            "grist.bibliography-options.v1.schema.json",
            false,
            crate::bibliography::BibliographyOptions
        );
        add!(
            "bibliography-citation-resolution",
            "bibliography",
            SchemaVersion::BIBLIOGRAPHY_CITATION_RESOLUTION_V1,
            SchemaKind::Payload,
            "grist.bibliography-citation-resolution.v1.schema.json",
            false,
            crate::bibliography::CitationResolutionReport
        );
    }
    #[cfg(feature = "basin")]
    {
        add!(
            "basin-code-graph",
            "basin-code-graph",
            "grist/basin-code-graph/v1",
            SchemaKind::Graph,
            "grist.basin-code-graph.v1.schema.json",
            true,
            crate::basin::CodeGraph
        );
        add!(
            "basin-walk-options",
            "basin-walk-options",
            "grist/basin-walk-options/v1",
            SchemaKind::Options,
            "grist.basin-walk-options.v1.schema.json",
            false,
            crate::basin::WalkOptions
        );
    }

    entries.push(Registration {
        descriptor: SchemaDescriptor {
            name: "dynamic-event-explorer-dataset".into(),
            family: "dynamic-event-explorer-dataset".into(),
            schema_version: "dynamic-event-explorer/dataset/v1".into(),
            kind: SchemaKind::Payload,
            file_name: "dynamic-event-explorer.dataset.v1.schema.json".into(),
            canonical_example: "examples/schema-canonical-examples.v1.json#/examples/dynamic-event-explorer-dataset".into(),
            backend_sensitive: false,
        },
        generator: || {
            serde_json::from_str(include_str!(
                "../../schemas/dynamic-event-explorer.dataset.v1.schema.json"
            ))
            .expect("checked-in external schema is valid JSON")
        },
    });

    entries.sort_by(|left, right| left.descriptor.name.cmp(&right.descriptor.name));
    entries
}
